.TH TUNESVIEWER "1" "March 2012" "TunesViewer" "User Commands"
.SH NAME
TunesViewer \- program to access media and podcasts from iTunes U
.SH SYNOPSIS
.B tunesviewer
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-s\fR SEARCH, \fB\-\-search\fR=\fISEARCH\fR
Give terms to search for university media in iTunes U.
.TP
\fB\-p\fR SEARCH, \fB\-\-search\-podcast\fR=\fISEARCH\fR
Give terms to search on podcasts in iTunes U.
.TP
\fB\-d\fR DOWNLOADFILE, \fB\-\-download\fR=\fIDOWNLOADFILE\fR
Download HTML only, without using any GUI.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Output debug information.
.TP
\fB\-V\fR, \fB\-\-version\fR
Output version number and exit.
.SH BUGS
.PP
There are probably many. The authors kindly ask to be informed about
incorrect behavior that you see.
.SH SEE ALSO
.BR mplayer (1) ,
.BR rhythmbox (1) ,
.BR vlc (1)
.SH AUTHOR
TunesViewer was written by Luke Brian, and Rogério Brito with the (much
appreciated and kind) help of other contributors. This manpage was written
by Rog\['e]rio Brito <rbrito@ime.usp.br>.
